export const LOGIN_SUCCESS ='LOGIN_SUCCESS'
export const LOGIN_ERROR ='LOGIN_ERROR'
export const SIGNOUT_SUCCESS ='SIGNOUT_SUCCESS'
export const CREATE_PROJECT = 'ADD_PROJECT'
export const CREATE_PROJECT_ERROR="CREATE_PROJECT_ERROR"